// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLxy1ktiwB8E1BjW5OniYudijyZRZ5GA',
    appId: '1:77431499514:web:178f1587c9693c8f3f3743',
    messagingSenderId: '77431499514',
    projectId: 'chat-9b4df',
    authDomain: 'chat-9b4df.firebaseapp.com',
    storageBucket: 'chat-9b4df.appspot.com',
    measurementId: 'G-TVKHJPXEVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4kUlcoit_WY3QtUJ4mct_6hgy-KUObM',
    appId: '1:77431499514:android:fea88084e1d5491b3f3743',
    messagingSenderId: '77431499514',
    projectId: 'chat-9b4df',
    storageBucket: 'chat-9b4df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhq3WjeUbPMdC1jNpelKsPu8xrtHGWhtk',
    appId: '1:77431499514:ios:059bb8bb079369453f3743',
    messagingSenderId: '77431499514',
    projectId: 'chat-9b4df',
    storageBucket: 'chat-9b4df.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
